export default [
        {
            id:1,
            title:"33PX",
            order:"font-size:33px;",
            group:1,
        },
        {
            id:2,
            title:"26PX",
            order:"font-size:26px;",
            group:1,
        },
        {
            id:3,
            title:"22PX",
            order:"font-size:22px;",
            group:1,
        },
        {
            id:5,
            title:"bold",
            order:"font-weight: bold;",
            group:2,
        },
        {
            id:6,
            title:"italic",
            order:"font-style: italic;",
            group:2,
        },
        {
            id:7,
            title:"strike",
            order:"text-decoration: underline;",
            group:4,
        },
        {
            id:8,
            title:"left",
            order:"text-align:left;",
            group:5,
        },
        {
            id:9,
            title:"center",
            order:"text-align:center;",
            group:5,
        },
        {
            id:10,
            title:"right",
            order:"text-align:right;",
            group:5,
        },
        {
            id:11,
            title:"justify",
            order:"text-align:justify;",
            group:5,
        },
]